# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TelinkCloudSigMeshLib' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TelinkCloudSigMeshLib

  pod 'AFNetworking'
  pod 'OpenSSL-Universal'
end

target 'TelinkSigMeshLib' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TelinkSigMeshLib
  pod 'OpenSSL-Universal'

  target 'TelinkSigMeshLibTests' do
    # Pods for testing
  end

end
